# Site settings
name: Nicolas Guillen
title: Nicolas Guillen | Desarrollador de sofware Full Stack
description: Programador de software full stack interesado en la creación de producto y experiencia de desarrollador.
url: https://nicolascalev.com
baseurl: ''
email: nicolascalevg@gmail.com
cover: https://nicolascalev.com/img/og.png
logo: /img/emojis/technologist.png
resume: /resume.pdf
social:
  - title: email
    url: mailto:nicolascalevg@gmail.com
  - title: instagram
    url: https://instagram.com/nicolascalev
  - title: github
    url: https://github.com/nicolascalev
  - title: linkedin
    url: https://www.linkedin.com/in/nicolascalev

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
